export enum PermissionKey {
  VIEW_BILL = 'VIEW_BILL',
  MANAGE_BILL = 'MANAGE_BILL',
  PAY_BILL = 'PAY_BILL',
  COMMENT_BILL = 'COMMENT_BILL',
  // Vendors
  VIEW_VENDOR = 'VIEW_VENDOR',
  MANAGE_VENDOR = 'MANAGE_VENDOR',
  // User
  VIEW_USER = 'VIEW_USER',
  MANAGE_USER = 'MANAGE_USER',
  // Role
  VIEW_ROLE = 'VIEW_ROLE',
  MANAGE_ROLE = 'MANAGE_ROLE',
  // Group
  VIEW_GROUP = 'VIEW_GROUP',
  MANAGE_GROUP = 'MANAGE_GROUP',
  // Company
  VIEW_COMPANY = 'VIEW_COMPANY',
  MANAGE_COMPANY = 'MANAGE_COMPANY',
  // Integration
  VIEW_INTEGRATION = 'VIEW_INTEGRATION',
  MANAGE_CONNECTION = 'MANAGE_CONNECTION',
  EXECUTE_CONNECTION_SYNC = 'EXECUTE_CONNECTION_SYNC',
  // Reports
  VIEW_REPORT = 'VIEW_REPORT',
  CREATE_REPORT = 'CREATE_REPORT',
  EXPORT_REPORT = 'EXPORT_REPORT',
  // Approval Workflow
  VIEW_APPROVAL_WORKFLOW = 'VIEW_APPROVAL_WORKFLOW',
  MANAGE_APPROVAL_WORKFLOW = 'MANAGE_APPROVAL_WORKFLOW'
}
