export type OriginAccountType = {
  id: string;
  externalId: string;
  bankId: string;
  bankCode: string;
  redactedAccountNumber: string;
  accountName: string;
  countryId: string;
  countryExternalId: string;
  county: string;
  state: string;
  iban: string;
  zipCode: string;
  city: string;
  block: string;
  branch: string;
  street: string;
  currencyId: string;
  generalLedgerAccountId: string;
  generalLedgerAccountExternalId: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};
